### ISSUE TITLE
[Feature Request]: Docker image for linux/arm/v7

### ISSUE THREAD

**Issue by mookeyj79** [TheDarthMole/upswake#29]
## Enhancement of issue

Provide a linux/arm/v7 docker image
## Solution

Provide a linux/arm/v7 docker image
## Alternatives

No response
## Additional Context

Love this project a lot, but I'm trying to run it on a Raspberry Pi. I can build from source successfully, but it would be more convenient to be able to pull from DockerHub directly. Thank you again!

**Comment by TheDarthMole** [comment]
Hey @mookeyj79, Thanks for your request. I've released a new version on DockerHub but unfortunately I don't have a arm/v7 device to test this. Can you see if the application runs on your Raspberry Pi?

**Comment by mookeyj79** [comment]
Working great! Thank you!
